export const message = {
    idNotFoundMessage: "Please provide user id",
    userNotFoundMessage: "User not found",
    userCreatedMessage: "user created successfully",
    userAlreadyExistMessage: "User already exist",
    otpNotFoundMessage: "Please provide otp",
    userAlreadyVerifiedMessage: "user already verified",
    otpAttemptsExceededMessage: "Too many attempts. Please try again later",
    missingFieldMessage: "Please provide all required fields",
    loginLockedMessage: "Login attempts exceeded, Please try again later",
    badAuthMessage: "Invalid email or password",
    invalidOtpMessage: "Otp invalid",
    otpExpiredMessage: "Otp expired, Generate new otp",
    userVerifiedMessage: "User verified successfully",
    loginSuccessfulMessage: "Login successful",
    logoutMessage: "Logged out successfully",
    userProfileFoundMessage: "User profile found",
    userProfileUpdatedMessage: "User profile updated successfully",
    unAuthorizedMessage:"Please login to access this resource",
    badAuthMessage: "Invalid email or password",
    userNotVerifiedMessage:"user is not verified,Please first verify",
    otpSendMessage:"otp sent successfully",
    postNotFoundMessage:"No post found",
    postFoundMessage:"Post found successfully",
    postsNotFoundMessage:"No posts found",
    postsFoundMessage:"Posts found successfully",
    postCreatedMessage:"Post created successfully",
    notAuthorizedMessage:"Not Authorized",
    postDeletedMessage:"Post deleted successfully",
    imageNotFoundMessage:"Please provide an image",
  };
  
  